/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LegionRouteImport } from './routes/legion'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as MarketplaceAgentIdRouteImport } from './routes/marketplace.$agentId'
import { Route as DocsSectionRouteImport } from './routes/docs.$section'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardLedgerRouteImport } from './routes/dashboard.ledger'
import { Route as DashboardFleetRouteImport } from './routes/dashboard.fleet'
import { Route as DashboardAgentsRouteImport } from './routes/dashboard.agents'
import { Route as DashboardLedgerBatchRouteImport } from './routes/dashboard.ledger.$batch'
import { Route as DashboardFleetInstanceIdRouteImport } from './routes/dashboard.fleet.$instanceId'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LegionRoute = LegionRouteImport.update({
  id: '/legion',
  path: '/legion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const MarketplaceAgentIdRoute = MarketplaceAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DocsSectionRoute = DocsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DocsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerRoute = DashboardLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFleetRoute = DashboardFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsRoute = DashboardAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLedgerBatchRoute = DashboardLedgerBatchRouteImport.update({
  id: '/$batch',
  path: '/$batch',
  getParentRoute: () => DashboardLedgerRoute,
} as any)
const DashboardFleetInstanceIdRoute =
  DashboardFleetInstanceIdRouteImport.update({
    id: '/$instanceId',
    path: '/$instanceId',
    getParentRoute: () => DashboardFleetRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/legion': typeof LegionRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/fleet': typeof DashboardFleetRouteWithChildren
  '/dashboard/ledger': typeof DashboardLedgerRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/$section': typeof DocsSectionRoute
  '/marketplace/$agentId': typeof MarketplaceAgentIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/dashboard/fleet/$instanceId': typeof DashboardFleetInstanceIdRoute
  '/dashboard/ledger/$batch': typeof DashboardLedgerBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legion': typeof LegionRoute
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/fleet': typeof DashboardFleetRouteWithChildren
  '/dashboard/ledger': typeof DashboardLedgerRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/$section': typeof DocsSectionRoute
  '/marketplace/$agentId': typeof MarketplaceAgentIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/dashboard/fleet/$instanceId': typeof DashboardFleetInstanceIdRoute
  '/dashboard/ledger/$batch': typeof DashboardLedgerBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/docs': typeof DocsRouteWithChildren
  '/legion': typeof LegionRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/dashboard/agents': typeof DashboardAgentsRoute
  '/dashboard/fleet': typeof DashboardFleetRouteWithChildren
  '/dashboard/ledger': typeof DashboardLedgerRouteWithChildren
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/docs/$section': typeof DocsSectionRoute
  '/marketplace/$agentId': typeof MarketplaceAgentIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/dashboard/fleet/$instanceId': typeof DashboardFleetInstanceIdRoute
  '/dashboard/ledger/$batch': typeof DashboardLedgerBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/docs'
    | '/legion'
    | '/marketplace'
    | '/dashboard/agents'
    | '/dashboard/fleet'
    | '/dashboard/ledger'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/docs/$section'
    | '/marketplace/$agentId'
    | '/dashboard/'
    | '/docs/'
    | '/marketplace/'
    | '/dashboard/fleet/$instanceId'
    | '/dashboard/ledger/$batch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legion'
    | '/dashboard/agents'
    | '/dashboard/fleet'
    | '/dashboard/ledger'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/docs/$section'
    | '/marketplace/$agentId'
    | '/dashboard'
    | '/docs'
    | '/marketplace'
    | '/dashboard/fleet/$instanceId'
    | '/dashboard/ledger/$batch'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/docs'
    | '/legion'
    | '/marketplace'
    | '/dashboard/agents'
    | '/dashboard/fleet'
    | '/dashboard/ledger'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/docs/$section'
    | '/marketplace/$agentId'
    | '/dashboard/'
    | '/docs/'
    | '/marketplace/'
    | '/dashboard/fleet/$instanceId'
    | '/dashboard/ledger/$batch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
  LegionRoute: typeof LegionRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legion': {
      id: '/legion'
      path: '/legion'
      fullPath: '/legion'
      preLoaderRoute: typeof LegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/marketplace/$agentId': {
      id: '/marketplace/$agentId'
      path: '/$agentId'
      fullPath: '/marketplace/$agentId'
      preLoaderRoute: typeof MarketplaceAgentIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/docs/$section': {
      id: '/docs/$section'
      path: '/$section'
      fullPath: '/docs/$section'
      preLoaderRoute: typeof DocsSectionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger': {
      id: '/dashboard/ledger'
      path: '/ledger'
      fullPath: '/dashboard/ledger'
      preLoaderRoute: typeof DashboardLedgerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fleet': {
      id: '/dashboard/fleet'
      path: '/fleet'
      fullPath: '/dashboard/fleet'
      preLoaderRoute: typeof DashboardFleetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents': {
      id: '/dashboard/agents'
      path: '/agents'
      fullPath: '/dashboard/agents'
      preLoaderRoute: typeof DashboardAgentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ledger/$batch': {
      id: '/dashboard/ledger/$batch'
      path: '/$batch'
      fullPath: '/dashboard/ledger/$batch'
      preLoaderRoute: typeof DashboardLedgerBatchRouteImport
      parentRoute: typeof DashboardLedgerRoute
    }
    '/dashboard/fleet/$instanceId': {
      id: '/dashboard/fleet/$instanceId'
      path: '/$instanceId'
      fullPath: '/dashboard/fleet/$instanceId'
      preLoaderRoute: typeof DashboardFleetInstanceIdRouteImport
      parentRoute: typeof DashboardFleetRoute
    }
  }
}

interface DashboardFleetRouteChildren {
  DashboardFleetInstanceIdRoute: typeof DashboardFleetInstanceIdRoute
}

const DashboardFleetRouteChildren: DashboardFleetRouteChildren = {
  DashboardFleetInstanceIdRoute: DashboardFleetInstanceIdRoute,
}

const DashboardFleetRouteWithChildren = DashboardFleetRoute._addFileChildren(
  DashboardFleetRouteChildren,
)

interface DashboardLedgerRouteChildren {
  DashboardLedgerBatchRoute: typeof DashboardLedgerBatchRoute
}

const DashboardLedgerRouteChildren: DashboardLedgerRouteChildren = {
  DashboardLedgerBatchRoute: DashboardLedgerBatchRoute,
}

const DashboardLedgerRouteWithChildren = DashboardLedgerRoute._addFileChildren(
  DashboardLedgerRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAgentsRoute: typeof DashboardAgentsRoute
  DashboardFleetRoute: typeof DashboardFleetRouteWithChildren
  DashboardLedgerRoute: typeof DashboardLedgerRouteWithChildren
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgentsRoute: DashboardAgentsRoute,
  DashboardFleetRoute: DashboardFleetRouteWithChildren,
  DashboardLedgerRoute: DashboardLedgerRouteWithChildren,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DocsRouteChildren {
  DocsSectionRoute: typeof DocsSectionRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSectionRoute: DocsSectionRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceAgentIdRoute: typeof MarketplaceAgentIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceAgentIdRoute: MarketplaceAgentIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
  LegionRoute: LegionRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
